spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/tasks?sslmode=disable
    username: sqladmin
    password: secret
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 4
      connection-test-query: SELECT 1
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/dbchangelog.xml
  sql:
    init:
      platform: postgres
management:
  endpoints:
    web:
      base-path: /
  endpoint:
    health:
      show-details: always
      show-components: always