#!/usr/bin/env python3

import argparse
import os.path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('dirs', metavar='DIR', nargs='+')
    args = parser.parse_args()

    paths = list(args.dirs)
    queue = list(args.dirs)
    while queue:
        d = queue.pop(0)
        try:
            deps_filename = os.path.join(d, '_DEPS')
            with open(deps_filename) as f:
                more = [
                    os.path.normpath(os.path.join(d, p))
                    for p in map(str.strip, f.readlines()) if p
                ]

                queue[:0] = more
                paths[:0] = more
        except FileNotFoundError: ...

    for p in paths:
        print(p)


if __name__ == '__main__':
    main()
